requirements = {'req_big': 20, 'req_small': 14, 'big_punish': 2, 'small_punish': 2}
iterations = 10
population_size = 10
clone_rate = 0.01
selection_rate = 0.2
max_big_machines = 30
max_small_machines = 30
min_working_time = 1
max_working_time = 16
max_bonus = 0.5
max_haste = 0.5
